### ISSUE TITLE
Support WebKitGTK+ version 2.6

### ISSUE THREAD

**Issue by joachifm** [joachifm/cl-webkit#16]
WebKit 2.6 bumps the .so to 4.0.0 and removes WebKitWebGroup.
It seems not many distros ship 2.6 quite yet, so we might want to maintain
backwards compatibility with 2.4.5 for a while.
Before beginning to work on this we need to be able to do condtional compilation
based on the currently loaded webkit version.

**Comment by Ambrevar** [comment]
We support the 4.0.0 .so now and every distribution is expected to ship a modern WebKitGTK.
Closing.
