### ISSUE TITLE
Support Mac OSX

### ISSUE THREAD

**Issue by AeroNotix** [joachifm/cl-webkit#27]
I don't have a mac or use OSX but I had a bug report on IRC for Lispkit that mentioned that cl-webkit didn't seem to properly find the libraries for OSX.

**Comment by Ambrevar** [comment]
@jmercouris can run is on macOS, but it must be run from the main thread.
Could be a cl-cffi-gtk issue.

**Comment by jmercouris** [comment]
the dylibs were missing from the `define-foreign-library` definition in package.lisp, they are now there, and it works on macOS! :-)
