### ISSUE TITLE
CFFI load of .so file

### ISSUE THREAD

**Issue by ahungry** [joachifm/cl-webkit#31]
Arch Linux uses libwebkit2gtk-4.0.so, while this looks for a max of 3.0 - is it possible to support 4.0?

**Comment by joachifm** [comment]
The library init (see webkit2/init.lisp) is configured to prefer libwebkit2gtk-4.0.so.
What is the error message upon loading the library?

**Comment by ahungry** [comment]
joachifm <notifications@github.com> writes:

> The library init (see webkit2/init.lisp) is configured to prefer
> libwebkit2gtk-4.0.so.  What is the error message upon loading the
> library?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/joachifm/cl-webkit/issues/31#issuecomment-73198592

Maybe it was a caching issue when setting up lispkit via the makefile -
upon initial 'make' I didn't have libwebkit2 installed (I had
libwebkit).

After installing and re-running the make commands, it still said no lib
found, which was resolved by manually symlinking 4.0 to a 3.0 symlink
(not best practice obviously, but it got past the error).

-- 
Matthew Carter (m@ahungry.com)
http://ahungry.com

**Comment by ahungry** [comment]
Just tried on a fresh git clone of lispkit (which loads this as a dependency) and received the same issue, so it was not caching related.

Maybe lispkit has an old forked copy of cl-webkit it uses though, so I'll close for now until I test under a clone of this repo myself.
