### ISSUE TITLE
Handle g-errors consistently

### ISSUE THREAD

**Issue by aartaka** [joachifm/cl-webkit#44]
I've seen `glib:with-g-error` macro being used in `webkit2/webkit2.web-view.lisp`, but it's not present in recent commits, even though there is code referencing g-errors.

Should this macro be used everywhere g-error is used? It seems to be quite useful for debugging.

Adding to that, how do we represent `g-errors`? Is it plain `:pointer` or `(:pointer (:struct glib:g-error))` constuction?

**Comment by Ambrevar** [comment]
I agree that we should probably use it.  Wanna send a patch? :)

I'm not sure about the representation, I guess we've got to test.  There are a few `(gerror :pointer)` in the code, so I guess that should do the job.
