### ISSUE TITLE
webkit_user_content_manager_register_script_message_handle misspelled!

### ISSUE THREAD

**Issue by loafofpiecrust** [joachifm/cl-webkit#54]
I'm working on a project where I need to communicate between the web page and CL code. I noticed that I can't hook up script message handlers with this library because `webkit_user_content_manager_register_script_message_handle` is misspelled in the API and should be `webkit_user_content_manager_register_script_message_handler` (note the R at the end).

**Comment by Ambrevar** [comment]
Good catch, fixed in 4f1d5a182764d327e74bcaa3a11b5e351f123b48, thanks for reporting!
