### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [joachifm/cl-webkit#55]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 094cbcbbc435a429978aa64599d431c07a01bad7

*cl-webkit2* fails to build with the following error:

```
Unhandled UNBOUND-VARIABLE in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A18083}>: The variable WEBKIT-WEB-PROCESS-TERMINATION-REASON is unbound.

```

[Full log here](http://report.quicklisp.org/2021-05-28/failure-report/cl-webkit.html)

**Comment by Ambrevar** [comment]
Fixed with https://github.com/joachifm/cl-webkit/commit/4b62c490438919c487bd549c2a68c702adcd5b98.  Thanks for reporting! :)
