### ISSUE TITLE
Support javascript that does not return a string.

### ISSUE THREAD

**Issue by Ambrevar** [joachifm/cl-webkit#56]
Calling `webkit-web-view-evaluate-javascript` over a snippet that returns a value that cannot be coerced to string raises an error.
Try evaluating `document;` to see what I mean.

The code in `javascript-evaluation-complete` is outdated, we can see it was taken from https://webkitgtk.org/reference/webkit2gtk/2.5.1/WebKitWebView.html#webkit-web-view-run-javascript-finish, while the latest doc suggests https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-run-javascript-finish.

I suggest we do the following:

- Test if the return value is a string.  If so, convert to string as we currently do.
- If not, pass the pointer directly to the callback.

What about other atomic types like numbers?
@jmercouris @aartaka Thoughts?

See also #52.

**Comment by jmercouris** [comment]
I guess we could update it, I don't see a problem with that. I would like to always return a string. Trying to be clever about what type to return may lead to problems.

**Comment by Ambrevar** [comment]
You mean always return a string when we can, e.g. convert a number to string?
Because in the general case, it does not make sense to return a string, e.g. with `document;`.

**Comment by jmercouris** [comment]
Yes, that's what I mean, when the object can be written to a string, do so.

**Comment by aartaka** [comment]
Oh wait, so we can transform the return values of the `webkit_web_view_run_javascript` to `JSCValue`s!? I've been missing that one thing for a long time!

Let me brush the dust off the JSCore bindings I accidentally made, and we'll have a full toolbox for dealing with `JSCValue`s! ٩(^ᴗ^)۶

**Comment by aartaka** [comment]
With this thing being possible, I'm on the side of returing most meaningful Lisp values possible (with numbers and `null`-s and `undefined`-s; and, if we get radical, parsing JS objects to plists/hash-tables).

**Comment by Ambrevar** [comment]
We got to make sure there will be no impedance mismatch between JS and
CL though.

For instance, the empty list, null and undefined don't naturally map 1-to-1 
between the two languages.

I suggest to look at the JSON libraries.  Maybe leverage one library directly?
Reference: https://sabracrolleton.github.io/json-review

**Comment by aartaka** [comment]
Fair point!
