### ISSUE TITLE
Errors on the custom URL thread make the whole WebKit process crash

### ISSUE THREAD

**Issue by aartaka** [joachifm/cl-webkit#64]
While all the custom URL handling is happening on a separate thread asynchronously, any condition raised there segfaults the whole process. This should not happen, given that we use `handler-case` there. Should we also add a case for `condition`s? How do we ensure stability of erroring callbacks?

**Comment by Ambrevar** [comment]
Where do we use `handler-case`?  Can you point at the code?

An unhandled condition on a background thread will crash SBCL indeed.

> Should we also add a case for conditions? 

What do you mean?

Note that `ignore-errors` and `(handler-case ... (error` don't catch all conditions.  If you want to catch everything, you've got to catch `T`.

**Comment by aartaka** [comment]
What I meant was the `handler-case` in `uri-scheme-processed` callback in `webkit2/webkit.uri-scheme-request.lisp`. It was indeed only catching errors, while any raised condition that wasn't an error was crushing it. 

Given the brutality of this bug, how about releasing a new version and moving Nyxt to it?

**Comment by Ambrevar** [comment]
Agreed, and that's right on time for 2.2.4! :)
