### ISSUE TITLE
Implicit dependency on `alexandria`

### ISSUE THREAD

**Issue by aadcg** [joachifm/cl-webkit#67]
Commit 639c6cbfced77ff94bbae43bfaf720f61eb0caa2 introduced a dependency on `alexandria` but that change was not propagated to `cl-webkit2.asd`.

Since the only symbol used is `alexandria:with-gensyms`, I'd suggest adding this macro to the codebase instead of dragging the whole library.

CC @aartaka

**Comment by aartaka** [comment]
It's not implicit, it's propagated. `cffi` depends on `alexandria`, so no need to change anything.

**Comment by Ambrevar** [comment]
Well, to be nitpicky it's better to be explicit about your deps, because if some day cffi removes its Alexandria dep, it will break cl-webkit.
