### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [joachifm/cl-webkit#68]
Building with SBCL 2.2.11.160-65fe8bb77 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id d60d43443115dfb5ff658e71c9611ce43aa83efe

*cl-webkit2* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Symbol "G-VARIANT-GET-TYPE" not found in the GLIB package. Line: 25, Column: 59, File-Position: 796 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/cl-webkit/4167ad8cd968969185f1b3a05808b43a8fa0b9c5/cl-webkit-20221227-git/webkit2/util.lisp" {101F5AFBC3}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001710003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-webkit2" "util">

```

*cl-webkit2/test* fails to build with the following error:

```
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001710003}>: No package named "CFFI"

```

[Full log here](http://report.quicklisp.org/2022-12-27/failure-report/cl-webkit.html)

**Comment by aartaka** [comment]
The `cl-webkit2/test` failure should be fixed with 998cf6bee56f0cdf392f590f8b233aaaea397257. 

The `cl-webkit2` one is extremely weird, though... @quicklisp, what's the fork/commit of `cl-cffi-gtk` you're building `cl-webkit2` against?

**Comment by quicklisp** [comment]
I'm temporarily using https://github.com/sharplispers/cl-cffi-gtk head due
to https://github.com/crategus/cl-cffi-gtk/issues/102

**Comment by aartaka** [comment]
That's a tricky situation: 
- Ferada port of `cl-cffi-gtk` (that `cl-webkit2` was used/tested with most of the time) has `glib:g-variant-get-type` function, but has no `glib:g-variant-type` (it only has a structure of that name).
- While Crategus port of `cl-cffi-gtk` (forked to sharplispers) only has `glib:g-variant-type`, having no `glib:g-variant-get-type`.
- Given that those ports don't push anything to `*features*` I cannot even add a feature-macro to use either of the functions.

@quicklisp, is it possible to add a feature keyword (something like `:sharplispers-cl-cffi-gtk`?) to the sharplispers port so that `cl-webkit2` can distinguish between the Ferada port and sharplispers one?

Alternatively, maybe package Ferada port for Quicklisp too?

**Comment by quicklisp** [comment]
I don't think adding features upstream is the best approach. You could use
something like (find-symbol ...) to establish features that you need.

Sorry for this hassle - Quicklisp was using Ferada, then there was a
request to use the "real" version from Crategus, then cffi updates broke
both, and I opted to temporarily fork the supposed "real" one - it's a pain.

**Comment by aartaka** [comment]
Oh god, the whole GVariant API is differing between the ports. It feels
impossible to write a fork-portable code with this |_・)

**Comment by aartaka** [comment]
So yeah, @quicklisp, any option to still depend on Ferada's port for cl-webkit? Porting it to Crategus/sharplispers one is not a one-liner at all.

**Comment by quicklisp** [comment]
I'll see about the Ferada option. That might also need some patching to
work with the newest CFFI.

**Comment by quicklisp** [comment]
Ok, I switched back to Ferada, and now I get this:

READ error during COMPILE-FILE: Symbol "G-VARIANT-GET-TYPE" not found
in the GLIB package.


Log here:
http://report.quicklisp.org/2023-02-03/failure-report/cl-webkit.html#cl-webkit2

**Comment by aartaka** [comment]
That is highly weird. You sure it's on Ferada port? Maybe some cache left from Crategus one? I had this error once when loading `cl-webkit2`, but that was because of Crategus port being in ~/common-lisp/ :D

**Comment by quicklisp** [comment]
Ah, it was a problem on my end. I changed the repo without clearing a cache
and it led to this error. After fixing the cache problem, cl-webkit builds
cleanly again. Thanks.

**Comment by aartaka** [comment]
Cool! Closing this then :)
