### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by mmontone** [joachifm/cl-webkit#69]
Demo refers to a `webkit:webkit-website-data-manager` that is not available anymore. Is there a fix?

**Comment by mmontone** [comment]
Also `webkit:webkit-user-content-manager-add-style-sheet`. Maybe more symbols.

**Comment by aartaka** [comment]
You sure they are not available? They are still in the codebase...

Any load errors when loading cl-webkit2? Any warnings? The only guess I have is that it fails in the middle of loading, thus only having half of the symbols it otherwise would.

**Comment by mmontone** [comment]
I was loading an old repo! My bad. Apologies.
