### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aadcg** [joachifm/cl-webkit#72]
Indeed, the only change that landed is rather small - bcf97b8ad0dc0e2e28139f77f1e2ec398704479e.

The reason why I'm pushing for a new release is that I'm growing tired of asking Nyxt users which version of WebKitGTK they're using. They usually share the output of `nyxt --system-information`, which would render the question useless.

Thanks.

**Comment by Ambrevar** [comment]
Done with https://github.com/joachifm/cl-webkit/commit/3d1e8156e5b1d29b07b3a8fecb868318bdfdbcbf.  I'll update the Guix package just now.
